// Test generated by RoostGPT for test zb-js-test using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { shallow } from 'enzyme';
import Result from './Result';

describe('Result component', () => {
  let component;

  beforeEach(() => {
    component = shallow(<Result />);
  });

  afterEach(() => {
    component.unmount();
  });

  it('should have correct initial state', () => {
    expect(component.state()).toEqual({
      candidates: [],
      results: [],
      total_votes: 0,
    });
  });

  it('state should not be null', () => {
    expect(component.state()).not.toBeNull();
  });
});
