// Test generated by RoostGPT for test zb-js-test using AI Type Open AI and AI Model gpt-4

import React from "react";
import { render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import App from './App';

describe('App', () => {
  test('renders Home component when at /', () => {
    render(
      <MemoryRouter initialEntries={['/']}>
        <App />
      </MemoryRouter>
    );

    expect(screen.getByText('Home')).toBeInTheDocument();
  });

  test('renders Result component when at /result', () => {
    render(
      <MemoryRouter initialEntries={['/result']}>
        <App />
      </MemoryRouter>
    );

    expect(screen.getByText('Result')).toBeInTheDocument();
  });

  test('redirects to / when visiting non-existing routes', () => {
    render(
      <MemoryRouter initialEntries={['/non-existing-route']}>
        <App />
      </MemoryRouter>
    );

    expect(screen.getByText('Home')).toBeInTheDocument();
  });
});
