// Test generated by RoostGPT for test zb-js-test using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import { createMemoryHistory } from 'history'
import { Router } from 'react-router-dom'
import Home from './Home';

describe('Home Component', () => {
  test('should redirect to /result when showResults is called', () => {
    const history = createMemoryHistory();
    const { getByTestId } = render(
      <Router history={history}>
        <Home />
      </Router>
    );
    
    fireEvent.click(getByTestId('result-button'));
    
    expect(history.location.pathname).toBe('/result');
  });

  test('should stay on the same page if showResults is not called', () => {
    const history = createMemoryHistory();
    const { getByTestId } = render(
      <Router history={history}>
        <Home />
      </Router>
    );
    
    expect(history.location.pathname).toBe('/');
  });
});
